apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
     containers:
     - name: frontend
       image: ahmadali616/frontend11:latest
       ports:
       - containerPort: 80
       env:
       - name: VITE_BACKEND_URL
         value: "http://backend:5000"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
