apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3M=   # rootpass
  mysql-user: Z3Vlc3Q=               # guest
  mysql-password: Z3Vlc3QxMjM=       # guest123
